# Generated by Django 2.1.7 on 2019-04-20 09:56

from django.db import migrations, models
import django_enumfield.db.fields
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='allowed_courses', to='users.Department', verbose_name='Departments allowed to register the course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students_gender',
            field=django_enumfield.db.fields.EnumField(default=0, enum=users.models.GenderTypeAllowed, verbose_name='Genders allowed to register the course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subfields',
            field=models.ManyToManyField(blank=True, related_name='allowed_courses', to='users.Subfield', verbose_name='Subfields allowed to register the course'),
        ),
        migrations.AlterUniqueTogether(
            name='field',
            unique_together={('head_department', 'title', 'degree')},
        ),
        migrations.AlterUniqueTogether(
            name='subfield',
            unique_together={('field', 'title')},
        ),
    ]
