# Generated by Django 2.1.7 on 2019-04-24 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190424_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrier',
            old_name='admission_type',
            new_name='admission_type_num',
        ),
    ]
