# Generated by Django 2.1.7 on 2019-04-16 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190416_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='subfield',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.SubField'),
            preserve_default=False,
        ),
    ]
