# Generated by Django 2.1.7 on 2019-04-16 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_carrier_subfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='departments',
            field=models.ManyToManyField(related_name='fields', to='users.Department'),
        ),
        migrations.AlterField(
            model_name='field',
            name='head_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_fields', to='users.Department'),
        ),
    ]
