# Generated by Django 2.1.7 on 2019-04-16 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190416_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveSmallIntegerField()),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Carrier')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carriers', models.ManyToManyField(related_name='registered_courses', through='users.Attends', to='users.Carrier')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='users.Department')),
                ('departments', models.ManyToManyField(related_name='allowed_courses', to='users.Department')),
                ('field_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='users.FieldCourse')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PreliminaryRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Carrier')),
                ('field_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.FieldCourse')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveSmallIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Course')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='subfield',
            name='field_courses',
            field=models.ManyToManyField(related_name='subfields', to='users.FieldCourse'),
        ),
        migrations.AddField(
            model_name='preliminaryregistration',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Term'),
        ),
        migrations.AddField(
            model_name='course',
            name='professors',
            field=models.ManyToManyField(related_name='courses', through='users.Teaches', to='users.Professor'),
        ),
        migrations.AddField(
            model_name='course',
            name='subfields',
            field=models.ManyToManyField(related_name='allowed_courses', to='users.SubField'),
        ),
        migrations.AddField(
            model_name='course',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Term'),
        ),
        migrations.AddField(
            model_name='attends',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Course'),
        ),
        migrations.AddField(
            model_name='attends',
            name='grades',
            field=models.ManyToManyField(blank=True, to='users.Grade'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='pre_reg_field_courses',
            field=models.ManyToManyField(blank=True, related_name='carriers', through='users.PreliminaryRegistration', to='users.FieldCourse'),
        ),
    ]
